### ISSUE TITLE
"again" is spelt "agian" in "Play again"

### ISSUE THREAD

**Issue by itsmorethantech** [MulesGaming/minecraft-wordle#1]
![image](https://github.com/MulesGaming/minecraft-wordle/assets/82797019/59fc2aa0-7d50-4e63-ad11-07999d61111d)
![image](https://github.com/MulesGaming/minecraft-wordle/assets/82797019/4b0736c8-3007-493d-96ca-4eb0935df531)

**Comment by MulesGaming** [comment]
Fixed. Thanks for the report.
