### ISSUE TITLE
"variants" is spelled "varintents" in desription of "biomes"

### ISSUE THREAD

**Issue by 5-u5** [MulesGaming/minecraft-wordle#2]
In the facts paragraph of the term "biomes" there is a spelling error
![Screenshot_20231227-232908](https://github.com/MulesGaming/minecraft-wordle/assets/117954449/60c7a109-72d2-49fb-bb04-3b1d7d892e75)

**Comment by MulesGaming** [comment]
Should be fixed in the next commit. This is embarrassing.
