### ISSUE TITLE
Play Again button not always working

### ISSUE THREAD

**Issue by S-y1vie** [MulesGaming/minecraft-wordle#24]
When clicking play again my browser asked whether I wanna stay on this site or leave. Both options didnt do anything. However, then hitting the change theme button and playing again caused this issue not to happen after playing through again and clicking the button again.

**Comment by MulesGaming** [comment]
The "_play again_" button should just simulate a page reload. What happens if you reload the page normally? What browser are you using?

**Comment by MulesGaming** [comment]
This looks like a problem on your end.
