### ISSUE TITLE
Not working due to failing json parse/unresolved merge conflict

### ISSUE THREAD

**Issue by Janbuller** [MulesGaming/minecraft-wordle#32]
The website currently doesn't work with the following error code in the firefox browser console

![image](https://github.com/MulesGaming/minecraft-wordle/assets/10071881/b8de3123-b6ae-49b0-bb04-6c84e34a9560)

The effect of this is that the game doesn't choose a word, making the game impossible to win.

This seems to be due to an unresolved merge conflict in the following lines of code

https://github.com/MulesGaming/minecraft-wordle/blob/bec95cdd2f7be87dc239a6a01b44fb4848e870fc/words.json#L13-L19

**Comment by MulesGaming** [comment]
This should be fixed now.
