### ISSUE TITLE
No word was chosen

### ISSUE THREAD

**Issue by Etharomea** [MulesGaming/minecraft-wordle#33]
Clicked play again and went about guessing, and became very confused when there was no vowels in the word. Thought maybe it was pulling a random letter combo from somewhere, but turns out there just simply wasn't a word
![2023-12-29_14_13_12](https://github.com/MulesGaming/minecraft-wordle/assets/24962666/901e571b-b9cd-4ce0-8838-2f609b0b4d18)
![2023-12-29 14_24_20](https://github.com/MulesGaming/minecraft-wordle/assets/24962666/73865edf-97c9-47a1-88c8-1dcf66de25cd)

**Comment by MulesGaming** [comment]
Sorry about that. Should be fixed now.
