### ISSUE TITLE
Word suggestions:

### ISSUE THREAD

**Issue by its-Jaxx** [MulesGaming/minecraft-wordle#37]
### Books:
`{"word": ["b","o","o","k","s"], "about": "Books are items that play an important role for enchanting, used to craft the enchanting table itself as well as bookshelves required to power it up. Alternatively, books themselves can be enchanted in order to store and apply enchantments. A book can also be crafted into a book and quill, which allows players to write and keep text.", "wiki": "https://minecraft.wiki/w/Book"},`

### Chest:
`{"word": ["c","h","e","s","t"], "about": "A chest is a block used to store items.", "wiki": "https://minecraft.wiki/w/Chest"},`

### Scute:
`{"word": ["s","c","u","t","e"], "about": "Scutes are items that baby turtles drop when they grow into adults. They can be used to craft turtle shells which can be used to brew the potion of the Turtle Master.", "wiki": "https://minecraft.wiki/w/Chest"},`

### Paper:
`{"word": ["p","a","p","e","r"], "about": "Paper is an item crafted from sugar cane, required for crafting books, maps, firework rockets and banner patterns.", "wiki": "https://minecraft.wiki/w/Paper"},`

### Wheat:
`{"word": ["w","h","e","a","t"], "about": "Wheat is an item primarily obtained by harvesting fully-grown wheat crops. It is used for crafting as well as to feed certain animals.", "wiki": "https://minecraft.wiki/w/Wheat"},`

**Comment by MulesGaming** [comment]
Looks good. I modified the description of the chest to add information about double chests and updated the scute description for the armadillo scute.
