### ISSUE TITLE
Only have 5-letter words

### ISSUE THREAD

**Issue by Gamemaster322** [MulesGaming/minecraft-wordle#4]
"Boats" was apparently the word. "Boat" is what is in MC

**Comment by fandziax** [comment]
Yeah that's how plural forms work. When you have two boats, they're _boats_, not _a_ boat.

**Comment by Kecomirs** [comment]
What he means is- That it should be singular as stated as in the Minecraft Wiki
For example- [Roses](minecraft.wiki/w/Roses) would be Rosebush because thats the way it is in the Minecraft Wiki, however it's not 5 letters.
He thinks that it should be more than 5 characters.

**Comment by MulesGaming** [comment]
Plural's are used as words in the Wordle. The words are not necessarily the same form as the wiki says to allow for more words.
