### ISSUE TITLE
Duplicate letters aren't highlighted properly 

### ISSUE THREAD

**Issue by Apceniy** [MulesGaming/minecraft-wordle#5]
For example, if the target word is "lever" and you input "sheep", the second "e" will be green as normal, but the first "e" isn't highlighted at all.

**Comment by AreaDenial** [comment]
Can confirm. I would have guessed SHEEP sooner, but since the second E in SEEDY wasn't highlighted, I believed there was only one E in the word.
![image](https://github.com/MulesGaming/minecraft-wordle/assets/32404366/4c54fca7-99c5-44a8-b1fe-5279ae7568d8)

**Comment by Roshag** [comment]
+1 for igloo

**Comment by MulesGaming** [comment]
Ok, thank you. I'll add this to my list of things to fix.

**Comment by MulesGaming** [comment]
It took a rewrite of the letter checking engine but it should be fixed now :)
